site_name: Arduino för ungdomar

repo_url: https://github.com/richelbilderbeek/arduino_foer_ungdomar
edit_uri: blob/main/docs/

nav:
  - Välkommen: index.md
  - Kapitel:
    - Översiktet: kapitel/README.md
    - kapitel/01_anvaendning_av_den_inbyggda_lysdioden/README.md
    - kapitel/02_anvaendning_av_en_multimeter/README.md
    - kapitel/03_anslutning_av_en_lysdiod/README.md
    - kapitel/04_programmering_av_en_lysdiod/README.md
    - kapitel/05_anslutning_av_flera_lysdioder/README.md
    - kapitel/06_anvaendning_av_flera_lysdioder/README.md
    - kapitel/07_maetning_av_en_knapp/README.md
    - kapitel/08_anslutning_av_en_knapp/README.md
    - kapitel/09_anvaendning_av_en_knapp/README.md
    - kapitel/10_maetning_av_en_vridmotstaand/README.md
    - kapitel/11_anslutning_av_en_vridmotstaand/README.md
    - kapitel/12_anvaendning_av_en_vridmotstaand/README.md
    - kapitel/13_maetning_av_en_joystick/README.md
    - kapitel/14_anslutning_av_en_joystick/README.md
    - kapitel/15_anvaendning_av_en_joystick/README.md
    - kapitel/16_maetning_av_en_ldr/README.md
    - kapitel/17_anslutning_av_en_ldr/README.md
    - kapitel/18_anvaendning_av_en_ldr/README.md
    - kapitel/19_anslutning_av_en_servo/README.md
    - kapitel/20_maetning_av_en_servo/README.md
    - kapitel/21_anvaendning_av_en_servo/README.md
    - kapitel/22_maetning_av_en_relae/README.md
    - kapitel/23_anslutning_av_en_relae/README.md
    - kapitel/24_anvaendning_av_en_relae/README.md
    - kapitel/25_maetning_av_en_dc_motor/README.md
    - kapitel/26_anslutning_av_en_dc_motor/README.md
    - kapitel/27_anvaendning_av_en_dc_motor/README.md
    - kapitel/28_maetning_av_en_avstaandssensor/README.md
    - kapitel/29_anslutning_av_en_avstaandssensor/README.md
    - kapitel/30_anvaendning_av_en_avstaandssensor/README.md
    - kapitel/31_maetning_av_neopixels/README.md
    - kapitel/32_anslutning_av_en_avstaandssensor/README.md
    - kapitel/33_anvaendning_av_neopixels/README.md
    - kapitel/34_maetning_av_en_kapacitiv_knapp/README.md
    - kapitel/35_anslutning_av_en_kapacitiv_knapp/README.md
    - kapitel/36_anvaendning_av_en_kapacitiv_knapp/README.md
    - kapitel/37_maetning_av_en_lcd/README.md
    - kapitel/38_anslutning_av_en_lcd/README.md
    - kapitel/39_anvaendning_av_en_lcd/README.md
    - kapitel/40_maetning_av_en_stegmotor/README.md
    - kapitel/41_anslutning_av_en_stegmotor/README.md
    - kapitel/42_anvaendning_av_en_stegmotor/README.md
  - Andra kapitel:
    - kapitel/arduino_till_processing/README.md
    - kapitel/kapacitiv_sensor_1/README.md
    - kapitel/kapacitiv_sensor_2/README.md
    - kapitel/kapacitiv_sensor_3/README.md
    - kapitel/ky-038_mic/README.md
    - kapitel/multimeter/README.md
    - kapitel/neo_pixel_1/README.md
    - kapitel/robot_arm/README.md
    - kapitel/robot_arm/text_for_pdf.md
    - kapitel/sju_segment_display/README.md
    - kapitel/stegmotor_1/README.md
    - kapitel/vagn_som_undviker_hinder/README.md
    - kapitel/FSR/README.md
    - kapitel/LCD2/README.md
    - kapitel/LCD3/README.md
    - kapitel/LCD3/dutch.md
    - kapitel/LDR/README.md
    - kapitel/Laser/README.md
    - kapitel/NeoPixel2/README.md
    - kapitel/Potmeter/README.md
    - kapitel/RFID1/README.md
    - kapitel/RFID2/README.md
    - kapitel/SerialMonitor1/README.md
    - kapitel/arduino_som_isp/README.md
    - kapitel/bare_bone_arduino/README.md
    - kapitel/breadboard/README.md
    - kapitel/chatroom/README.md
    - kapitel/foerord/README.md
    - kapitel/for_loop/README.md
    - kapitel/tone/README.md
  - Böcker: boecker/README.md
  - Lektionkort: lektionskort/README.md
  - Vanliga frågor: faq.md
  - Misc:
    - Bidragsgivarna: bidragsgivarna.md
    - Code of conduct: CODE_OF_CONDUCT.md
    - Contributing: CONTRIBUTING.md
    - learning_line.md
    - Licence: LICENSE
    - logo/README.md
    - Scripts: scripts/README.md

not_in_nav: |
  scripts/build/*.md
  kapitel/x*
  kapitel/framsidor/framsida_*
  kapitel/BlinkSnelheid/README.md
  kapitel/tone/README.md
  reflections/2*
  kapitel/BlinkSnelheid/README.md
  kapitel/Regenboog/README.md
  kapitel/StroomdeeltjeSpelen1/README.md

theme:
  name: material
  greetings: Välkommen till Arduino för ungdomar
  font:
    text: Lato
    code: JetBrains Mono
  palette:
    primary: blue

  # Keyboard shortcuts for navigation, from https://www.mkdocs.org/user-guide/choosing-your-theme/
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

  logo: logo/arduino_community_logo_white_background.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.share      
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view

markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      
